/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectakhir;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Togami
 */
public class Checkout extends javax.swing.JFrame {

    /** Creates new form DataPelanggan */
    public Checkout() {
        initComponents();
        loadData();
    }

    
     public void loadData(){
        try{
            KonekMYSQL konek = new KonekMYSQL();
            java.sql.Connection c = konek.getKoneksi(); 
            Statement s = c.createStatement();
            String sql = "SELECT * FROM pelanggan";
            ResultSet r = s.executeQuery(sql);
            while(r.next()){
              
              String data[] = {r.getString("id"),r.getString("no_ktp"), r.getString("no_hp"), r.getString("no_kamar"), r.getString("nama_satu"), r.getString("nama_dua"), r.getString("jenis_kamar"), r.getString("tgl_checkin"), r.getString("tgl_checkout")};
       
              DefaultTableModel tblModel = (DefaultTableModel)Tabel.getModel();
              tblModel.addRow(data);
            }
            r.close();
            s.close();
        }catch(SQLException e){
            System.out.println("terjadi error");
        }
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        Tcari = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        sort = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        ASC = new javax.swing.JCheckBox();
        DESC = new javax.swing.JCheckBox();
        Tubah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Tktp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Thp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Tkamar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Tnamasatu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Tnamadua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Tjeniskamar = new javax.swing.JTextField();
        Lmenu32 = new javax.swing.JPanel();
        Menuside32 = new javax.swing.JLabel();
        Reservasi32 = new javax.swing.JButton();
        Restoran32 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        Thome = new javax.swing.JButton();
        jLabel120 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Tclose = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "No. Ktp", "No. Hp", "No. Kamar", "Nama 1", "Nama 2", "Jenis Kamar", "Tgl Checkin", "Tgl Checkout"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel);
        if (Tabel.getColumnModel().getColumnCount() > 0) {
            Tabel.getColumnModel().getColumn(0).setResizable(false);
            Tabel.getColumnModel().getColumn(0).setPreferredWidth(2);
            Tabel.getColumnModel().getColumn(1).setResizable(false);
            Tabel.getColumnModel().getColumn(2).setResizable(false);
            Tabel.getColumnModel().getColumn(3).setResizable(false);
            Tabel.getColumnModel().getColumn(4).setResizable(false);
            Tabel.getColumnModel().getColumn(5).setResizable(false);
            Tabel.getColumnModel().getColumn(6).setResizable(false);
            Tabel.getColumnModel().getColumn(7).setResizable(false);
            Tabel.getColumnModel().getColumn(8).setResizable(false);
        }

        Tcari.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Tcari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TcariMouseClicked(evt);
            }
        });

        cari.setText("Cari");
        cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cariMouseClicked(evt);
            }
        });

        sort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no_ktp", "no_hp", "no_kamar", "nama_satu", "nama_dua", "jenis_kamar", "tgl_checkin", "tgl_checkout" }));
        sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sort by");

        ASC.setText("ASC");
        ASC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ASCMouseClicked(evt);
            }
        });

        DESC.setText("DESC");
        DESC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DESCMouseClicked(evt);
            }
        });

        Tubah.setText("Checkout");
        Tubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TubahMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No. Ktp");

        Tktp.setEditable(false);
        Tktp.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No. Hp");

        Thp.setEditable(false);
        Thp.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No. Kamar");

        Tkamar.setEditable(false);
        Tkamar.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama 1");

        Tnamasatu.setEditable(false);
        Tnamasatu.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama 2");

        Tnamadua.setEditable(false);
        Tnamadua.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jenis Kamar");

        Tjeniskamar.setEditable(false);
        Tjeniskamar.setBackground(new java.awt.Color(204, 204, 204));

        Lmenu32.setBackground(new java.awt.Color(54, 70, 78));
        Lmenu32.setToolTipText("");

        Menuside32.setIcon(new javax.swing.ImageIcon("D:\\Code\\Java\\SideBar\\src\\Icons\\icons8-menu-30.png")); // NOI18N

        Reservasi32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Reservasi32.setForeground(new java.awt.Color(255, 255, 255));
        Reservasi32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/default.png"))); // NOI18N
        Reservasi32.setText("Reservasi");
        Reservasi32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Reservasi32.setMinimumSize(new java.awt.Dimension(170, 40));
        Reservasi32.setPreferredSize(new java.awt.Dimension(170, 40));
        Reservasi32.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hover.png"))); // NOI18N
        Reservasi32.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/selected.png"))); // NOI18N
        Reservasi32.setSelected(true);
        Reservasi32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reservasi32ActionPerformed(evt);
            }
        });

        Restoran32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Restoran32.setForeground(new java.awt.Color(255, 255, 255));
        Restoran32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/default.png"))); // NOI18N
        Restoran32.setText("Restoran");
        Restoran32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Restoran32.setPreferredSize(new java.awt.Dimension(170, 40));
        Restoran32.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hover.png"))); // NOI18N
        Restoran32.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/selected.png"))); // NOI18N
        Restoran32.setSelected(true);
        Restoran32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Restoran32ActionPerformed(evt);
            }
        });

        jButton66.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton66.setForeground(new java.awt.Color(255, 255, 255));
        jButton66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/default.png"))); // NOI18N
        jButton66.setText("Kamar");
        jButton66.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton66.setPreferredSize(new java.awt.Dimension(170, 40));
        jButton66.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hover.png"))); // NOI18N
        jButton66.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/selected.png"))); // NOI18N
        jButton66.setSelected(true);

        jButton67.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton67.setForeground(new java.awt.Color(255, 255, 255));
        jButton67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/default.png"))); // NOI18N
        jButton67.setText("Laporan");
        jButton67.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton67.setMinimumSize(new java.awt.Dimension(170, 40));
        jButton67.setPreferredSize(new java.awt.Dimension(170, 40));
        jButton67.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hover.png"))); // NOI18N
        jButton67.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/selected.png"))); // NOI18N
        jButton67.setSelected(true);

        Thome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Thome.setForeground(new java.awt.Color(255, 255, 255));
        Thome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/default.png"))); // NOI18N
        Thome.setText("Home");
        Thome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Thome.setMinimumSize(new java.awt.Dimension(170, 40));
        Thome.setPreferredSize(new java.awt.Dimension(170, 40));
        Thome.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hover.png"))); // NOI18N
        Thome.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/selected.png"))); // NOI18N
        Thome.setSelected(true);
        Thome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThomeMouseClicked(evt);
            }
        });

        jLabel120.setBackground(new java.awt.Color(255, 255, 255));
        jLabel120.setForeground(new java.awt.Color(255, 255, 255));
        jLabel120.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hotel.png"))); // NOI18N

        javax.swing.GroupLayout Lmenu32Layout = new javax.swing.GroupLayout(Lmenu32);
        Lmenu32.setLayout(Lmenu32Layout);
        Lmenu32Layout.setHorizontalGroup(
            Lmenu32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lmenu32Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Lmenu32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lmenu32Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Menuside32))
                    .addGroup(Lmenu32Layout.createSequentialGroup()
                        .addGroup(Lmenu32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Thome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Restoran32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton67, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton66, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Reservasi32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 8, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lmenu32Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel120)
                .addGap(29, 29, 29))
        );
        Lmenu32Layout.setVerticalGroup(
            Lmenu32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lmenu32Layout.createSequentialGroup()
                .addComponent(Menuside32)
                .addGap(35, 35, 35)
                .addComponent(jLabel120)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(Thome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Reservasi32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Restoran32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        Tclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/remove.png"))); // NOI18N
        Tclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TcloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tclose)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tclose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Lmenu32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sort, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ASC)
                                .addGap(18, 18, 18)
                                .addComponent(DESC))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cari))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 56, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Tktp, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Thp, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Tkamar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Tnamadua, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Tnamasatu, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Tjeniskamar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(Tubah, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lmenu32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(Tktp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(Thp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(Tkamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(Tnamasatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(Tnamadua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(Tjeniskamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Tubah))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ASC)
                                    .addComponent(DESC)
                                    .addComponent(Tcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cari))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DESCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DESCMouseClicked
        ASC.setSelected(false);
        String Sort = sort.getSelectedItem().toString();
        Tabel.setModel(new DefaultTableModel(null, new String[]{
            "ID", "No. Ktp", "No. Hp", "No. Kamar", "Nama 1", "Nama 2", "Jenis Kamar", "Tgl Checkin", "Tgl Checkout"
        }));
        TableColumnModel columnModel = Tabel.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(2);
        try{
            KonekMYSQL konek = new KonekMYSQL();
            java.sql.Connection c = konek.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM pelanggan ORDER BY " + Sort + " DESC";
            ResultSet r = s.executeQuery(sql);
            while(r.next()){

                String data[] = {r.getString("id"), r.getString("no_ktp"), r.getString("no_hp"), r.getString("no_kamar"), r.getString("nama_satu"), r.getString("nama_dua"), r.getNString("jenis_kamar"), r.getString("tgl_checkin"), r.getString("tgl_checkout")};

                DefaultTableModel tblModel = (DefaultTableModel)Tabel.getModel();
                tblModel.addRow(data);
            }
            r.close();
            s.close();
        }catch(SQLException e){
            System.out.println("terjadi error Sort data");
        }
    }//GEN-LAST:event_DESCMouseClicked

    private void ASCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ASCMouseClicked
        DESC.setSelected(false);
        String Sort = sort.getSelectedItem().toString();
        Tabel.setModel(new DefaultTableModel(null, new String[]{
            "ID","No. Ktp", "No. Hp", "No. Kamar", "Nama 1", "Nama 2", "Jenis Kamar", "Tgl Checkin", "Tgl Checkout"
        }));
        TableColumnModel columnModel = Tabel.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(2);
        try{
            KonekMYSQL konek = new KonekMYSQL();
            java.sql.Connection c = konek.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM pelanggan ORDER BY " + Sort + " ASC";
            ResultSet r = s.executeQuery(sql);
            while(r.next()){

                String data[] = {r.getString("id"), r.getString("no_ktp"), r.getString("no_hp"), r.getString("no_kamar"), r.getString("nama_satu"), r.getString("nama_dua"), r.getNString("jenis_kamar"), r.getString("tgl_checkin"), r.getString("tgl_checkout")};

                DefaultTableModel tblModel = (DefaultTableModel)Tabel.getModel();
                tblModel.addRow(data);
            }
            r.close();
            s.close();
        }catch(SQLException e){
            System.out.println("terjadi error Sort data");
        }
    }//GEN-LAST:event_ASCMouseClicked

    private void sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortActionPerformed
        String Sort = sort.getSelectedItem().toString();
        Tabel.setModel(new DefaultTableModel(null, new String[]{
            "ID", "No. Ktp", "No. Hp", "No. Kamar", "Nama 1", "Nama 2", "Jenis Kamar", "Tgl Checkin", "Tgl Checkout"
        }));
        TableColumnModel columnModel = Tabel.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(2);
        try{
            KonekMYSQL konek = new KonekMYSQL();
            java.sql.Connection c = konek.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM pelanggan ORDER BY " + Sort;
            ResultSet r = s.executeQuery(sql);
            while(r.next()){

                String data[] = {r.getString("id"), r.getString("no_ktp"), r.getString("no_hp"), r.getString("no_kamar"), r.getString("nama_satu"), r.getString("nama_dua"), r.getString("jenis_kamar"), r.getString("tgl_checkin"), r.getString("tgl_checkout")};

                DefaultTableModel tblModel = (DefaultTableModel)Tabel.getModel();
                tblModel.addRow(data);
            }
            r.close();
            s.close();
        }catch(SQLException e){
            System.out.println("terjadi error Sort data");
        }
    }//GEN-LAST:event_sortActionPerformed

    private void cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariMouseClicked
        String kunci = Tcari.getText();
        Tabel.setModel(new DefaultTableModel(null, new String[]{
            "ID", "No. Ktp", "No. Hp", "No. Kamar", "Nama 1", "Nama 2", "Jenis Kamar", "Tgl Checkin", "Tgl Checkout"
        }));
        TableColumnModel columnModel = Tabel.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(2);
        try{
            KonekMYSQL konek = new KonekMYSQL();
            java.sql.Connection c = konek.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM pelanggan WHERE nama_satu LIKE " + "'%" + kunci + "%' OR no_ktp LIKE "  + "'%" + kunci + "%' OR no_hp LIKE "  + "'%" + kunci + "%' OR no_kamar LIKE" + "'%" + kunci + "%' OR nama_dua LIKE " + "'%" + kunci + "%' OR jenis_kamar LIKE "+ "'%" + kunci + "%'";
            ResultSet r = s.executeQuery(sql);
            while(r.next()){

                String data[] = {r.getString("id"), r.getString("no_ktp"), r.getString("no_hp"), r.getString("no_kamar"), r.getString("nama_satu"), r.getString("nama_dua"), r.getString("jenis_kamar"), r.getString("tgl_checkin"), r.getString("tgl_checkout")};

                DefaultTableModel tblModel = (DefaultTableModel)Tabel.getModel();
                tblModel.addRow(data);
            }
            r.close();
            s.close();
        }catch(SQLException e){
            System.out.println("terjadi error Search data");
        }
        
    }//GEN-LAST:event_cariMouseClicked

    private void TcariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TcariMouseClicked
        Tcari.setText("");
    }//GEN-LAST:event_TcariMouseClicked

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked
        int row = Tabel.getSelectedRow();
        String value1 = Tabel.getModel().getValueAt(row, 1).toString();
        String value2 = Tabel.getModel().getValueAt(row, 2).toString();
        String value3 = Tabel.getModel().getValueAt(row, 3).toString();
        String value4 = Tabel.getModel().getValueAt(row, 4).toString();
        String value5 = Tabel.getModel().getValueAt(row, 5).toString();
        String value6 = Tabel.getModel().getValueAt(row, 6).toString();

        Tktp.setText(value1);
        Thp.setText(value2);
        Tkamar.setText(value3);
        Tnamasatu.setText(value4);
        Tnamadua.setText(value5);
        Tjeniskamar.setText(value6);
    }//GEN-LAST:event_TabelMouseClicked

    private void TubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TubahMouseClicked
        int row = Tabel.getSelectedRow();
        String id = Tabel.getModel().getValueAt(row, 0).toString();
        
        int a=JOptionPane.showConfirmDialog(this,"Anda yakin?");  
        
        if (a==JOptionPane.YES_OPTION){
        
            try{
                KonekMYSQL konek = new KonekMYSQL();
                java.sql.Connection c = konek.getKoneksi();
                Statement s = c.createStatement();
                String sql = String.format("DELETE FROM pelanggan WHERE id='%s'", id);
                s.execute(sql);
            }catch(SQLException e){
                System.out.println("terjadi error delete data");
                System.out.println(e.getMessage());
            }

            Tabel.setModel(new DefaultTableModel(null, new String[]{
                "ID", "No. Ktp", "No. Hp", "No. Kamar", "Nama 1", "Nama 2", "Jenis Kamar", "Tgl Checkin", "Tgl Checkout"
            }));

            loadData();
            TableColumnModel columnModel = Tabel.getColumnModel();
            columnModel.getColumn(0).setPreferredWidth(2);
            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
            Tktp.setText("");
            Thp.setText("");
            Tkamar.setText("");
            Tnamasatu.setText("");
            Tnamadua.setText("");
            Tjeniskamar.setText("");
        }
    }//GEN-LAST:event_TubahMouseClicked

    private void Reservasi32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reservasi32ActionPerformed
        Reservasi reservasi = new Reservasi();
        reservasi.setVisible(true);
        reservasi.pack();
        reservasi.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_Reservasi32ActionPerformed

    private void Restoran32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Restoran32ActionPerformed
        // TODO add your handling code here:
        kasir_resto restoran = new kasir_resto();
        restoran.setVisible(true);
        restoran.pack();
        restoran.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_Restoran32ActionPerformed

    private void ThomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThomeMouseClicked
        Dashboard menu = new Dashboard();
        menu.setVisible(true);
        menu.pack();
        menu.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_ThomeMouseClicked

    private void TcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TcloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_TcloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ASC;
    private javax.swing.JCheckBox ASC1;
    private javax.swing.JCheckBox ASC10;
    private javax.swing.JCheckBox ASC11;
    private javax.swing.JCheckBox ASC12;
    private javax.swing.JCheckBox ASC13;
    private javax.swing.JCheckBox ASC14;
    private javax.swing.JCheckBox ASC15;
    private javax.swing.JCheckBox ASC16;
    private javax.swing.JCheckBox ASC2;
    private javax.swing.JCheckBox ASC3;
    private javax.swing.JCheckBox ASC4;
    private javax.swing.JCheckBox ASC5;
    private javax.swing.JCheckBox ASC6;
    private javax.swing.JCheckBox ASC7;
    private javax.swing.JCheckBox ASC8;
    private javax.swing.JCheckBox ASC9;
    private javax.swing.JCheckBox DESC;
    private javax.swing.JCheckBox DESC1;
    private javax.swing.JCheckBox DESC10;
    private javax.swing.JCheckBox DESC11;
    private javax.swing.JCheckBox DESC12;
    private javax.swing.JCheckBox DESC13;
    private javax.swing.JCheckBox DESC14;
    private javax.swing.JCheckBox DESC15;
    private javax.swing.JCheckBox DESC16;
    private javax.swing.JCheckBox DESC2;
    private javax.swing.JCheckBox DESC3;
    private javax.swing.JCheckBox DESC4;
    private javax.swing.JCheckBox DESC5;
    private javax.swing.JCheckBox DESC6;
    private javax.swing.JCheckBox DESC7;
    private javax.swing.JCheckBox DESC8;
    private javax.swing.JCheckBox DESC9;
    private javax.swing.JPanel Lmenu;
    private javax.swing.JPanel Lmenu1;
    private javax.swing.JPanel Lmenu10;
    private javax.swing.JPanel Lmenu11;
    private javax.swing.JPanel Lmenu12;
    private javax.swing.JPanel Lmenu13;
    private javax.swing.JPanel Lmenu14;
    private javax.swing.JPanel Lmenu15;
    private javax.swing.JPanel Lmenu16;
    private javax.swing.JPanel Lmenu17;
    private javax.swing.JPanel Lmenu18;
    private javax.swing.JPanel Lmenu19;
    private javax.swing.JPanel Lmenu2;
    private javax.swing.JPanel Lmenu20;
    private javax.swing.JPanel Lmenu21;
    private javax.swing.JPanel Lmenu22;
    private javax.swing.JPanel Lmenu23;
    private javax.swing.JPanel Lmenu24;
    private javax.swing.JPanel Lmenu25;
    private javax.swing.JPanel Lmenu26;
    private javax.swing.JPanel Lmenu27;
    private javax.swing.JPanel Lmenu28;
    private javax.swing.JPanel Lmenu29;
    private javax.swing.JPanel Lmenu3;
    private javax.swing.JPanel Lmenu30;
    private javax.swing.JPanel Lmenu31;
    private javax.swing.JPanel Lmenu32;
    private javax.swing.JPanel Lmenu4;
    private javax.swing.JPanel Lmenu5;
    private javax.swing.JPanel Lmenu6;
    private javax.swing.JPanel Lmenu7;
    private javax.swing.JPanel Lmenu8;
    private javax.swing.JPanel Lmenu9;
    private javax.swing.JLabel Menuside;
    private javax.swing.JLabel Menuside1;
    private javax.swing.JLabel Menuside10;
    private javax.swing.JLabel Menuside11;
    private javax.swing.JLabel Menuside12;
    private javax.swing.JLabel Menuside13;
    private javax.swing.JLabel Menuside14;
    private javax.swing.JLabel Menuside15;
    private javax.swing.JLabel Menuside16;
    private javax.swing.JLabel Menuside17;
    private javax.swing.JLabel Menuside18;
    private javax.swing.JLabel Menuside19;
    private javax.swing.JLabel Menuside2;
    private javax.swing.JLabel Menuside20;
    private javax.swing.JLabel Menuside21;
    private javax.swing.JLabel Menuside22;
    private javax.swing.JLabel Menuside23;
    private javax.swing.JLabel Menuside24;
    private javax.swing.JLabel Menuside25;
    private javax.swing.JLabel Menuside26;
    private javax.swing.JLabel Menuside27;
    private javax.swing.JLabel Menuside28;
    private javax.swing.JLabel Menuside29;
    private javax.swing.JLabel Menuside3;
    private javax.swing.JLabel Menuside30;
    private javax.swing.JLabel Menuside31;
    private javax.swing.JLabel Menuside32;
    private javax.swing.JLabel Menuside4;
    private javax.swing.JLabel Menuside5;
    private javax.swing.JLabel Menuside6;
    private javax.swing.JLabel Menuside7;
    private javax.swing.JLabel Menuside8;
    private javax.swing.JLabel Menuside9;
    private javax.swing.JButton Reservasi;
    private javax.swing.JButton Reservasi1;
    private javax.swing.JButton Reservasi10;
    private javax.swing.JButton Reservasi11;
    private javax.swing.JButton Reservasi12;
    private javax.swing.JButton Reservasi13;
    private javax.swing.JButton Reservasi14;
    private javax.swing.JButton Reservasi15;
    private javax.swing.JButton Reservasi16;
    private javax.swing.JButton Reservasi17;
    private javax.swing.JButton Reservasi18;
    private javax.swing.JButton Reservasi19;
    private javax.swing.JButton Reservasi2;
    private javax.swing.JButton Reservasi20;
    private javax.swing.JButton Reservasi21;
    private javax.swing.JButton Reservasi22;
    private javax.swing.JButton Reservasi23;
    private javax.swing.JButton Reservasi24;
    private javax.swing.JButton Reservasi25;
    private javax.swing.JButton Reservasi26;
    private javax.swing.JButton Reservasi27;
    private javax.swing.JButton Reservasi28;
    private javax.swing.JButton Reservasi29;
    private javax.swing.JButton Reservasi3;
    private javax.swing.JButton Reservasi30;
    private javax.swing.JButton Reservasi31;
    private javax.swing.JButton Reservasi32;
    private javax.swing.JButton Reservasi4;
    private javax.swing.JButton Reservasi5;
    private javax.swing.JButton Reservasi6;
    private javax.swing.JButton Reservasi7;
    private javax.swing.JButton Reservasi8;
    private javax.swing.JButton Reservasi9;
    private javax.swing.JButton Restoran;
    private javax.swing.JButton Restoran1;
    private javax.swing.JButton Restoran10;
    private javax.swing.JButton Restoran11;
    private javax.swing.JButton Restoran12;
    private javax.swing.JButton Restoran13;
    private javax.swing.JButton Restoran14;
    private javax.swing.JButton Restoran15;
    private javax.swing.JButton Restoran16;
    private javax.swing.JButton Restoran17;
    private javax.swing.JButton Restoran18;
    private javax.swing.JButton Restoran19;
    private javax.swing.JButton Restoran2;
    private javax.swing.JButton Restoran20;
    private javax.swing.JButton Restoran21;
    private javax.swing.JButton Restoran22;
    private javax.swing.JButton Restoran23;
    private javax.swing.JButton Restoran24;
    private javax.swing.JButton Restoran25;
    private javax.swing.JButton Restoran26;
    private javax.swing.JButton Restoran27;
    private javax.swing.JButton Restoran28;
    private javax.swing.JButton Restoran29;
    private javax.swing.JButton Restoran3;
    private javax.swing.JButton Restoran30;
    private javax.swing.JButton Restoran31;
    private javax.swing.JButton Restoran32;
    private javax.swing.JButton Restoran4;
    private javax.swing.JButton Restoran5;
    private javax.swing.JButton Restoran6;
    private javax.swing.JButton Restoran7;
    private javax.swing.JButton Restoran8;
    private javax.swing.JButton Restoran9;
    private javax.swing.JTable Tabel;
    private javax.swing.JTable Tabel1;
    private javax.swing.JTable Tabel10;
    private javax.swing.JTable Tabel11;
    private javax.swing.JTable Tabel12;
    private javax.swing.JTable Tabel13;
    private javax.swing.JTable Tabel14;
    private javax.swing.JTable Tabel15;
    private javax.swing.JTable Tabel16;
    private javax.swing.JTable Tabel2;
    private javax.swing.JTable Tabel3;
    private javax.swing.JTable Tabel4;
    private javax.swing.JTable Tabel5;
    private javax.swing.JTable Tabel6;
    private javax.swing.JTable Tabel7;
    private javax.swing.JTable Tabel8;
    private javax.swing.JTable Tabel9;
    private javax.swing.JTextField Tcari;
    private javax.swing.JTextField Tcari1;
    private javax.swing.JTextField Tcari10;
    private javax.swing.JTextField Tcari11;
    private javax.swing.JTextField Tcari12;
    private javax.swing.JTextField Tcari13;
    private javax.swing.JTextField Tcari14;
    private javax.swing.JTextField Tcari15;
    private javax.swing.JTextField Tcari16;
    private javax.swing.JTextField Tcari2;
    private javax.swing.JTextField Tcari3;
    private javax.swing.JTextField Tcari4;
    private javax.swing.JTextField Tcari5;
    private javax.swing.JTextField Tcari6;
    private javax.swing.JTextField Tcari7;
    private javax.swing.JTextField Tcari8;
    private javax.swing.JTextField Tcari9;
    private javax.swing.JLabel Tclose;
    private javax.swing.JButton Thome;
    private javax.swing.JTextField Thp;
    private javax.swing.JTextField Thp1;
    private javax.swing.JTextField Thp10;
    private javax.swing.JTextField Thp11;
    private javax.swing.JTextField Thp12;
    private javax.swing.JTextField Thp13;
    private javax.swing.JTextField Thp14;
    private javax.swing.JTextField Thp15;
    private javax.swing.JTextField Thp16;
    private javax.swing.JTextField Thp2;
    private javax.swing.JTextField Thp3;
    private javax.swing.JTextField Thp4;
    private javax.swing.JTextField Thp5;
    private javax.swing.JTextField Thp6;
    private javax.swing.JTextField Thp7;
    private javax.swing.JTextField Thp8;
    private javax.swing.JTextField Thp9;
    private javax.swing.JTextField Tjeniskamar;
    private javax.swing.JTextField Tjeniskamar1;
    private javax.swing.JTextField Tjeniskamar10;
    private javax.swing.JTextField Tjeniskamar11;
    private javax.swing.JTextField Tjeniskamar12;
    private javax.swing.JTextField Tjeniskamar13;
    private javax.swing.JTextField Tjeniskamar14;
    private javax.swing.JTextField Tjeniskamar15;
    private javax.swing.JTextField Tjeniskamar16;
    private javax.swing.JTextField Tjeniskamar2;
    private javax.swing.JTextField Tjeniskamar3;
    private javax.swing.JTextField Tjeniskamar4;
    private javax.swing.JTextField Tjeniskamar5;
    private javax.swing.JTextField Tjeniskamar6;
    private javax.swing.JTextField Tjeniskamar7;
    private javax.swing.JTextField Tjeniskamar8;
    private javax.swing.JTextField Tjeniskamar9;
    private javax.swing.JTextField Tkamar;
    private javax.swing.JTextField Tkamar1;
    private javax.swing.JTextField Tkamar10;
    private javax.swing.JTextField Tkamar11;
    private javax.swing.JTextField Tkamar12;
    private javax.swing.JTextField Tkamar13;
    private javax.swing.JTextField Tkamar14;
    private javax.swing.JTextField Tkamar15;
    private javax.swing.JTextField Tkamar16;
    private javax.swing.JTextField Tkamar2;
    private javax.swing.JTextField Tkamar3;
    private javax.swing.JTextField Tkamar4;
    private javax.swing.JTextField Tkamar5;
    private javax.swing.JTextField Tkamar6;
    private javax.swing.JTextField Tkamar7;
    private javax.swing.JTextField Tkamar8;
    private javax.swing.JTextField Tkamar9;
    private javax.swing.JTextField Tktp;
    private javax.swing.JTextField Tktp1;
    private javax.swing.JTextField Tktp10;
    private javax.swing.JTextField Tktp11;
    private javax.swing.JTextField Tktp12;
    private javax.swing.JTextField Tktp13;
    private javax.swing.JTextField Tktp14;
    private javax.swing.JTextField Tktp15;
    private javax.swing.JTextField Tktp16;
    private javax.swing.JTextField Tktp2;
    private javax.swing.JTextField Tktp3;
    private javax.swing.JTextField Tktp4;
    private javax.swing.JTextField Tktp5;
    private javax.swing.JTextField Tktp6;
    private javax.swing.JTextField Tktp7;
    private javax.swing.JTextField Tktp8;
    private javax.swing.JTextField Tktp9;
    private javax.swing.JTextField Tnamadua;
    private javax.swing.JTextField Tnamadua1;
    private javax.swing.JTextField Tnamadua10;
    private javax.swing.JTextField Tnamadua11;
    private javax.swing.JTextField Tnamadua12;
    private javax.swing.JTextField Tnamadua13;
    private javax.swing.JTextField Tnamadua14;
    private javax.swing.JTextField Tnamadua15;
    private javax.swing.JTextField Tnamadua16;
    private javax.swing.JTextField Tnamadua2;
    private javax.swing.JTextField Tnamadua3;
    private javax.swing.JTextField Tnamadua4;
    private javax.swing.JTextField Tnamadua5;
    private javax.swing.JTextField Tnamadua6;
    private javax.swing.JTextField Tnamadua7;
    private javax.swing.JTextField Tnamadua8;
    private javax.swing.JTextField Tnamadua9;
    private javax.swing.JTextField Tnamasatu;
    private javax.swing.JTextField Tnamasatu1;
    private javax.swing.JTextField Tnamasatu10;
    private javax.swing.JTextField Tnamasatu11;
    private javax.swing.JTextField Tnamasatu12;
    private javax.swing.JTextField Tnamasatu13;
    private javax.swing.JTextField Tnamasatu14;
    private javax.swing.JTextField Tnamasatu15;
    private javax.swing.JTextField Tnamasatu16;
    private javax.swing.JTextField Tnamasatu2;
    private javax.swing.JTextField Tnamasatu3;
    private javax.swing.JTextField Tnamasatu4;
    private javax.swing.JTextField Tnamasatu5;
    private javax.swing.JTextField Tnamasatu6;
    private javax.swing.JTextField Tnamasatu7;
    private javax.swing.JTextField Tnamasatu8;
    private javax.swing.JTextField Tnamasatu9;
    private javax.swing.JButton Tubah;
    private javax.swing.JButton Tubah1;
    private javax.swing.JButton Tubah10;
    private javax.swing.JButton Tubah11;
    private javax.swing.JButton Tubah12;
    private javax.swing.JButton Tubah13;
    private javax.swing.JButton Tubah14;
    private javax.swing.JButton Tubah15;
    private javax.swing.JButton Tubah16;
    private javax.swing.JButton Tubah2;
    private javax.swing.JButton Tubah3;
    private javax.swing.JButton Tubah4;
    private javax.swing.JButton Tubah5;
    private javax.swing.JButton Tubah6;
    private javax.swing.JButton Tubah7;
    private javax.swing.JButton Tubah8;
    private javax.swing.JButton Tubah9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cari;
    private javax.swing.JButton cari1;
    private javax.swing.JButton cari10;
    private javax.swing.JButton cari11;
    private javax.swing.JButton cari12;
    private javax.swing.JButton cari13;
    private javax.swing.JButton cari14;
    private javax.swing.JButton cari15;
    private javax.swing.JButton cari16;
    private javax.swing.JButton cari2;
    private javax.swing.JButton cari3;
    private javax.swing.JButton cari4;
    private javax.swing.JButton cari5;
    private javax.swing.JButton cari6;
    private javax.swing.JButton cari7;
    private javax.swing.JButton cari8;
    private javax.swing.JButton cari9;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JComboBox<String> sort;
    private javax.swing.JComboBox<String> sort1;
    private javax.swing.JComboBox<String> sort10;
    private javax.swing.JComboBox<String> sort11;
    private javax.swing.JComboBox<String> sort12;
    private javax.swing.JComboBox<String> sort13;
    private javax.swing.JComboBox<String> sort14;
    private javax.swing.JComboBox<String> sort15;
    private javax.swing.JComboBox<String> sort16;
    private javax.swing.JComboBox<String> sort2;
    private javax.swing.JComboBox<String> sort3;
    private javax.swing.JComboBox<String> sort4;
    private javax.swing.JComboBox<String> sort5;
    private javax.swing.JComboBox<String> sort6;
    private javax.swing.JComboBox<String> sort7;
    private javax.swing.JComboBox<String> sort8;
    private javax.swing.JComboBox<String> sort9;
    // End of variables declaration//GEN-END:variables

}
