/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectakhir;

import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    int pengunjung;
    public Dashboard() {
        initComponents();
        Component [] components = this.getContentPane().getComponents();
        
        for (Component component : components){
            if(component instanceof JButton){
                ((JButton)component).setUI(new BasicButtonUI());
            }
        }
        pengunjung=0;
        loadData();
    }
    
    
    
    public void loadData(){
        try{
            KonekMYSQL konek = new KonekMYSQL();
            java.sql.Connection c = konek.getKoneksi(); 
            Statement s = c.createStatement();
            String sql = "SELECT * FROM pelanggan";
            ResultSet r = s.executeQuery(sql);
            while(r.next()){
              
              pengunjung++;
       
              
            }
            String hasil = String.valueOf(pengunjung);
            Tpengunjung.setText(hasil);
            r.close();
            s.close();
        }catch(SQLException e){
            System.out.println("terjadi error");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel120 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Tclose = new javax.swing.JLabel();
        Lmenu = new javax.swing.JPanel();
        Menuside = new javax.swing.JLabel();
        Reservasi = new javax.swing.JButton();
        Restoran = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Thome = new javax.swing.JButton();
        jLabel121 = new javax.swing.JLabel();
        Tlogout = new javax.swing.JPanel();
        Tlogout2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Tpengunjung = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jLabel120.setBackground(new java.awt.Color(255, 255, 255));
        jLabel120.setForeground(new java.awt.Color(255, 255, 255));
        jLabel120.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hotel.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1234, 638));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FRONT OFFICE");

        Tclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/remove.png"))); // NOI18N
        Tclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TcloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(549, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(348, 348, 348)
                .addComponent(Tclose)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(Tclose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Lmenu.setBackground(new java.awt.Color(54, 70, 78));
        Lmenu.setToolTipText("");

        Menuside.setIcon(new javax.swing.ImageIcon("D:\\Code\\Java\\SideBar\\src\\Icons\\icons8-menu-30.png")); // NOI18N

        Reservasi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Reservasi.setForeground(new java.awt.Color(255, 255, 255));
        Reservasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/default.png"))); // NOI18N
        Reservasi.setText("Reservasi");
        Reservasi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Reservasi.setMinimumSize(new java.awt.Dimension(170, 40));
        Reservasi.setPreferredSize(new java.awt.Dimension(170, 40));
        Reservasi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hover.png"))); // NOI18N
        Reservasi.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/selected.png"))); // NOI18N
        Reservasi.setSelected(true);
        Reservasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservasiActionPerformed(evt);
            }
        });

        Restoran.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Restoran.setForeground(new java.awt.Color(255, 255, 255));
        Restoran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/default.png"))); // NOI18N
        Restoran.setText("Restoran");
        Restoran.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Restoran.setPreferredSize(new java.awt.Dimension(170, 40));
        Restoran.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hover.png"))); // NOI18N
        Restoran.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/selected.png"))); // NOI18N
        Restoran.setSelected(true);
        Restoran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestoranActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/default.png"))); // NOI18N
        jButton2.setText("Kamar");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPreferredSize(new java.awt.Dimension(170, 40));
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hover.png"))); // NOI18N
        jButton2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/selected.png"))); // NOI18N
        jButton2.setSelected(true);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/default.png"))); // NOI18N
        jButton4.setText("Laporan");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setMinimumSize(new java.awt.Dimension(170, 40));
        jButton4.setPreferredSize(new java.awt.Dimension(170, 40));
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hover.png"))); // NOI18N
        jButton4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/selected.png"))); // NOI18N
        jButton4.setSelected(true);

        Thome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Thome.setForeground(new java.awt.Color(255, 255, 255));
        Thome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/default.png"))); // NOI18N
        Thome.setText("Home");
        Thome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Thome.setMinimumSize(new java.awt.Dimension(170, 40));
        Thome.setPreferredSize(new java.awt.Dimension(170, 40));
        Thome.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hover.png"))); // NOI18N
        Thome.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/selected.png"))); // NOI18N
        Thome.setSelected(true);
        Thome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThomeMouseClicked(evt);
            }
        });

        jLabel121.setBackground(new java.awt.Color(255, 255, 255));
        jLabel121.setForeground(new java.awt.Color(255, 255, 255));
        jLabel121.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hotel.png"))); // NOI18N

        Tlogout.setBackground(new java.awt.Color(54, 70, 78));
        Tlogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TlogoutMouseClicked(evt);
            }
        });

        Tlogout2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logout.png"))); // NOI18N

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Logout");

        javax.swing.GroupLayout TlogoutLayout = new javax.swing.GroupLayout(Tlogout);
        Tlogout.setLayout(TlogoutLayout);
        TlogoutLayout.setHorizontalGroup(
            TlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TlogoutLayout.createSequentialGroup()
                .addComponent(Tlogout2)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TlogoutLayout.setVerticalGroup(
            TlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TlogoutLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(TlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tlogout2)))
        );

        javax.swing.GroupLayout LmenuLayout = new javax.swing.GroupLayout(Lmenu);
        Lmenu.setLayout(LmenuLayout);
        LmenuLayout.setHorizontalGroup(
            LmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LmenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel121)
                .addGap(29, 29, 29))
            .addGroup(LmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LmenuLayout.createSequentialGroup()
                        .addComponent(Tlogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LmenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Menuside))
                    .addGroup(LmenuLayout.createSequentialGroup()
                        .addGroup(LmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Restoran, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Reservasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Thome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 8, Short.MAX_VALUE))))
        );
        LmenuLayout.setVerticalGroup(
            LmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LmenuLayout.createSequentialGroup()
                .addComponent(Menuside)
                .addGap(18, 18, 18)
                .addComponent(jLabel121)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(Thome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Reservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Restoran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Tlogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/team.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ezgif.com-gif-maker.gif"))); // NOI18N

        Tpengunjung.setEditable(false);
        Tpengunjung.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Tpengunjung.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tpengunjung.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tpengunjung.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(624, 624, 624)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tpengunjung, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tpengunjung, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(236, 236, 236)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Lmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(43, 43, 43)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RestoranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestoranActionPerformed
        // TODO add your handling code here:
        kasir_resto restoran = new kasir_resto();
        restoran.setVisible(true);
        restoran.pack();
        restoran.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_RestoranActionPerformed

    private void ReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservasiActionPerformed
        Reservasi reservasi = new Reservasi();
        reservasi.setVisible(true);
        reservasi.pack();
        reservasi.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_ReservasiActionPerformed

    private void ThomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThomeMouseClicked
        Dashboard menu = new Dashboard();
        menu.setVisible(true);
        menu.pack();
        menu.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_ThomeMouseClicked

    private void TcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TcloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_TcloseMouseClicked

    private void TlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TlogoutMouseClicked
        Login masuk = new Login();
        masuk.setVisible(true);
        masuk.pack();
        masuk.setLocationRelativeTo(null);
       this.dispose(); 
    }//GEN-LAST:event_TlogoutMouseClicked

    int x = 210;
    int a = 0;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Lmenu;
    private javax.swing.JPanel Lmenu5;
    private javax.swing.JLabel Menuside;
    private javax.swing.JLabel Menuside5;
    private javax.swing.JButton Reservasi;
    private javax.swing.JButton Reservasi5;
    private javax.swing.JButton Restoran;
    private javax.swing.JButton Restoran5;
    private javax.swing.JLabel Tclose;
    private javax.swing.JButton Thome;
    private javax.swing.JPanel Tlogout;
    private javax.swing.JLabel Tlogout2;
    private javax.swing.JTextField Tpengunjung;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
