/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectakhir;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Togami
 */
public class DataPelanggan extends javax.swing.JFrame {

    /** Creates new form DataPelanggan */
    public DataPelanggan() {
        initComponents();
        loadData();
    }

    
     public void loadData(){
        try{
            KonekMYSQL konek = new KonekMYSQL();
            java.sql.Connection c = konek.getKoneksi(); 
            Statement s = c.createStatement();
            String sql = "SELECT * FROM pelanggan";
            ResultSet r = s.executeQuery(sql);
            while(r.next()){
              
              String data[] = {r.getString("id"),r.getString("no_ktp"), r.getString("no_hp"), r.getString("no_kamar"), r.getString("nama_satu"), r.getString("nama_dua"), r.getString("jenis_kamar"), r.getString("tgl_checkin"), r.getString("tgl_checkout")};
       
              DefaultTableModel tblModel = (DefaultTableModel)Tabel.getModel();
              tblModel.addRow(data);
            }
            r.close();
            s.close();
        }catch(SQLException e){
            System.out.println("terjadi error");
        }
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Tclose = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        Tcari = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        sort = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        ASC = new javax.swing.JCheckBox();
        DESC = new javax.swing.JCheckBox();
        Tubah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Tktp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Thp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Tkamar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Tnamasatu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Tnamadua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Tjeniskamar = new javax.swing.JTextField();
        Lmenu5 = new javax.swing.JPanel();
        Menuside5 = new javax.swing.JLabel();
        Reservasi5 = new javax.swing.JButton();
        Restoran5 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        Thome = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        Tclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/remove.png"))); // NOI18N
        Tclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TcloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tclose)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tclose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "No. Ktp", "No. Hp", "No. Kamar", "Nama 1", "Nama 2", "Jenis Kamar", "Tgl Checkin", "Tgl Checkout"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel);
        if (Tabel.getColumnModel().getColumnCount() > 0) {
            Tabel.getColumnModel().getColumn(0).setResizable(false);
            Tabel.getColumnModel().getColumn(0).setPreferredWidth(2);
            Tabel.getColumnModel().getColumn(1).setResizable(false);
            Tabel.getColumnModel().getColumn(2).setResizable(false);
            Tabel.getColumnModel().getColumn(3).setResizable(false);
            Tabel.getColumnModel().getColumn(4).setResizable(false);
            Tabel.getColumnModel().getColumn(5).setResizable(false);
            Tabel.getColumnModel().getColumn(6).setResizable(false);
            Tabel.getColumnModel().getColumn(7).setResizable(false);
            Tabel.getColumnModel().getColumn(8).setResizable(false);
        }

        Tcari.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Tcari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TcariMouseClicked(evt);
            }
        });

        cari.setText("Cari");
        cari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cariMouseClicked(evt);
            }
        });

        sort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no_ktp", "no_hp", "no_kamar", "nama_satu", "nama_dua", "jenis_kamar", "tgl_checkin", "tgl_checkout" }));
        sort.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sort by");

        ASC.setText("ASC");
        ASC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ASC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ASCMouseClicked(evt);
            }
        });

        DESC.setText("DESC");
        DESC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DESC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DESCMouseClicked(evt);
            }
        });

        Tubah.setText("Ubah");
        Tubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TubahMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No. Ktp");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No. Hp");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No. Kamar");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama 1");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama 2");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jenis Kamar");

        Lmenu5.setBackground(new java.awt.Color(54, 70, 78));
        Lmenu5.setToolTipText("");

        Menuside5.setIcon(new javax.swing.ImageIcon("D:\\Code\\Java\\SideBar\\src\\Icons\\icons8-menu-30.png")); // NOI18N

        Reservasi5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Reservasi5.setForeground(new java.awt.Color(255, 255, 255));
        Reservasi5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/default.png"))); // NOI18N
        Reservasi5.setText("Reservasi");
        Reservasi5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Reservasi5.setMinimumSize(new java.awt.Dimension(170, 40));
        Reservasi5.setPreferredSize(new java.awt.Dimension(170, 40));
        Reservasi5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hover.png"))); // NOI18N
        Reservasi5.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/selected.png"))); // NOI18N
        Reservasi5.setSelected(true);
        Reservasi5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reservasi5ActionPerformed(evt);
            }
        });

        Restoran5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Restoran5.setForeground(new java.awt.Color(255, 255, 255));
        Restoran5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/default.png"))); // NOI18N
        Restoran5.setText("Restoran");
        Restoran5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Restoran5.setPreferredSize(new java.awt.Dimension(170, 40));
        Restoran5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hover.png"))); // NOI18N
        Restoran5.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/selected.png"))); // NOI18N
        Restoran5.setSelected(true);
        Restoran5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Restoran5ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/default.png"))); // NOI18N
        jButton12.setText("Kamar");
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setPreferredSize(new java.awt.Dimension(170, 40));
        jButton12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hover.png"))); // NOI18N
        jButton12.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/selected.png"))); // NOI18N
        jButton12.setSelected(true);

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/default.png"))); // NOI18N
        jButton13.setText("Laporan");
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setMinimumSize(new java.awt.Dimension(170, 40));
        jButton13.setPreferredSize(new java.awt.Dimension(170, 40));
        jButton13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hover.png"))); // NOI18N
        jButton13.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/selected.png"))); // NOI18N
        jButton13.setSelected(true);

        Thome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Thome.setForeground(new java.awt.Color(255, 255, 255));
        Thome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/default.png"))); // NOI18N
        Thome.setText("Home");
        Thome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Thome.setMinimumSize(new java.awt.Dimension(170, 40));
        Thome.setPreferredSize(new java.awt.Dimension(170, 40));
        Thome.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hover.png"))); // NOI18N
        Thome.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/selected.png"))); // NOI18N
        Thome.setSelected(true);
        Thome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThomeMouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hotel.png"))); // NOI18N

        javax.swing.GroupLayout Lmenu5Layout = new javax.swing.GroupLayout(Lmenu5);
        Lmenu5.setLayout(Lmenu5Layout);
        Lmenu5Layout.setHorizontalGroup(
            Lmenu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lmenu5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Lmenu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lmenu5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Menuside5))
                    .addGroup(Lmenu5Layout.createSequentialGroup()
                        .addGroup(Lmenu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Thome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Restoran5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Reservasi5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 8, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lmenu5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(28, 28, 28))
        );
        Lmenu5Layout.setVerticalGroup(
            Lmenu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lmenu5Layout.createSequentialGroup()
                .addComponent(Menuside5)
                .addGap(41, 41, 41)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(Thome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Reservasi5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Restoran5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Lmenu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(452, 452, 452)
                        .addComponent(ASC)
                        .addGap(18, 18, 18)
                        .addComponent(DESC))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sort, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cari))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Tktp, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Thp, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Tkamar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Tnamadua, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Tnamasatu, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Tjeniskamar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Tubah, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lmenu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(Tktp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(Thp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(Tkamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(Tnamasatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(Tnamadua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(Tjeniskamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Tubah))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ASC)
                                    .addComponent(DESC)
                                    .addComponent(Tcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cari))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariMouseClicked
        String kunci = Tcari.getText();
        Tabel.setModel(new DefaultTableModel(null, new String[]{
                "ID", "No. Ktp", "No. Hp", "No. Kamar", "Nama 1", "Nama 2", "Jenis Kamar", "Tgl Checkin", "Tgl Checkout"
            }));
        TableColumnModel columnModel = Tabel.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(2);
        try{
            KonekMYSQL konek = new KonekMYSQL();
            java.sql.Connection c = konek.getKoneksi(); 
            Statement s = c.createStatement();
            String sql = "SELECT * FROM pelanggan WHERE nama_satu LIKE " + "'%" + kunci + "%' OR no_ktp LIKE "  + "'%" + kunci + "%' OR no_hp LIKE "  + "'%" + kunci + "%' OR no_kamar LIKE" + "'%" + kunci + "%' OR nama_dua LIKE " + "'%" + kunci + "%' OR jenis_kamar LIKE "+ "'%" + kunci + "%'";
            ResultSet r = s.executeQuery(sql);
            while(r.next()){
              
              String data[] = {r.getString("id"), r.getString("no_ktp"), r.getString("no_hp"), r.getString("no_kamar"), r.getString("nama_satu"), r.getString("nama_dua"), r.getString("jenis_kamar"), r.getString("tgl_checkin"), r.getString("tgl_checkout")};
       
              DefaultTableModel tblModel = (DefaultTableModel)Tabel.getModel();
              tblModel.addRow(data);
            }
            r.close();
            s.close();
        }catch(SQLException e){
            System.out.println("terjadi error Search data");
        }
    }//GEN-LAST:event_cariMouseClicked

    private void TcariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TcariMouseClicked
       Tcari.setText("");
    }//GEN-LAST:event_TcariMouseClicked

    private void sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortActionPerformed
        String Sort = sort.getSelectedItem().toString();
        Tabel.setModel(new DefaultTableModel(null, new String[]{
                 "ID", "No. Ktp", "No. Hp", "No. Kamar", "Nama 1", "Nama 2", "Jenis Kamar", "Tgl Checkin", "Tgl Checkout"
            }));
        TableColumnModel columnModel = Tabel.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(2);
        try{
            KonekMYSQL konek = new KonekMYSQL();
            java.sql.Connection c = konek.getKoneksi(); 
            Statement s = c.createStatement();
            String sql = "SELECT * FROM pelanggan ORDER BY " + Sort;
            ResultSet r = s.executeQuery(sql);
            while(r.next()){
              
              String data[] = {r.getString("id"), r.getString("no_ktp"), r.getString("no_hp"), r.getString("no_kamar"), r.getString("nama_satu"), r.getString("nama_dua"), r.getString("jenis_kamar"), r.getString("tgl_checkin"), r.getString("tgl_checkout")};
       
              DefaultTableModel tblModel = (DefaultTableModel)Tabel.getModel();
              tblModel.addRow(data);
            }
            r.close();
            s.close();
        }catch(SQLException e){
            System.out.println("terjadi error Sort data");
        }
    }//GEN-LAST:event_sortActionPerformed

    private void ASCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ASCMouseClicked
        DESC.setSelected(false);
       String Sort = sort.getSelectedItem().toString();
        Tabel.setModel(new DefaultTableModel(null, new String[]{
                 "ID","No. Ktp", "No. Hp", "No. Kamar", "Nama 1", "Nama 2", "Jenis Kamar", "Tgl Checkin", "Tgl Checkout"
            }));
        TableColumnModel columnModel = Tabel.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(2);
        try{
            KonekMYSQL konek = new KonekMYSQL();
            java.sql.Connection c = konek.getKoneksi(); 
            Statement s = c.createStatement();
            String sql = "SELECT * FROM pelanggan ORDER BY " + Sort + " ASC";
            ResultSet r = s.executeQuery(sql);
            while(r.next()){
              
              String data[] = {r.getString("id"), r.getString("no_ktp"), r.getString("no_hp"), r.getString("no_kamar"), r.getString("nama_satu"), r.getString("nama_dua"), r.getNString("jenis_kamar"), r.getString("tgl_checkin"), r.getString("tgl_checkout")};
       
              DefaultTableModel tblModel = (DefaultTableModel)Tabel.getModel();
              tblModel.addRow(data);
            }
            r.close();
            s.close();
        }catch(SQLException e){
            System.out.println("terjadi error Sort data");
        }
    }//GEN-LAST:event_ASCMouseClicked

    private void DESCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DESCMouseClicked
        ASC.setSelected(false);
        String Sort = sort.getSelectedItem().toString();
        Tabel.setModel(new DefaultTableModel(null, new String[]{
                 "ID", "No. Ktp", "No. Hp", "No. Kamar", "Nama 1", "Nama 2", "Jenis Kamar", "Tgl Checkin", "Tgl Checkout"
            }));
        TableColumnModel columnModel = Tabel.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(2);
        try{
            KonekMYSQL konek = new KonekMYSQL();
            java.sql.Connection c = konek.getKoneksi(); 
            Statement s = c.createStatement();
            String sql = "SELECT * FROM pelanggan ORDER BY " + Sort + " DESC";
            ResultSet r = s.executeQuery(sql);
            while(r.next()){
              
              String data[] = {r.getString("id"), r.getString("no_ktp"), r.getString("no_hp"), r.getString("no_kamar"), r.getString("nama_satu"), r.getString("nama_dua"), r.getNString("jenis_kamar"), r.getString("tgl_checkin"), r.getString("tgl_checkout")};
       
              DefaultTableModel tblModel = (DefaultTableModel)Tabel.getModel();
              tblModel.addRow(data);
            }
            r.close();
            s.close();
        }catch(SQLException e){
            System.out.println("terjadi error Sort data");
        }
    }//GEN-LAST:event_DESCMouseClicked

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked
        int row = Tabel.getSelectedRow();
        String value1 = Tabel.getModel().getValueAt(row, 1).toString();
        String value2 = Tabel.getModel().getValueAt(row, 2).toString();
        String value3 = Tabel.getModel().getValueAt(row, 3).toString();
        String value4 = Tabel.getModel().getValueAt(row, 4).toString();
        String value5 = Tabel.getModel().getValueAt(row, 5).toString();
        String value6 = Tabel.getModel().getValueAt(row, 6).toString();
        
        Tktp.setText(value1);
        Thp.setText(value2);
        Tkamar.setText(value3);
        Tnamasatu.setText(value4);
        Tnamadua.setText(value5);
        Tjeniskamar.setText(value6);
    }//GEN-LAST:event_TabelMouseClicked

    private void TubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TubahMouseClicked
        int row = Tabel.getSelectedRow();
        String ktp = Tktp.getText();
        String noHp = Thp.getText();
        String Nokamar = Tkamar.getText();
        String namasatu = Tnamasatu.getText();
        String namadua = Tnamadua.getText();
        String jenisKamar = Tjeniskamar.getText();
        String id = Tabel.getModel().getValueAt(row, 0).toString();
        
        int a=JOptionPane.showConfirmDialog(this,"Anda yakin?");  
        
        if (a==JOptionPane.YES_OPTION){
            try{
               KonekMYSQL konek = new KonekMYSQL();
               java.sql.Connection c = konek.getKoneksi(); 
               Statement s = c.createStatement();
               String sql = "UPDATE pelanggan SET no_ktp='%s', no_hp='%s', no_kamar='%s', nama_satu='%s', nama_dua='%s', jenis_kamar='%s' WHERE id='" + id + "'";
               sql = String.format(sql, ktp, noHp, Nokamar, namasatu, namadua, jenisKamar);
               s.execute(sql);
           }catch(SQLException e){
               System.out.println("terjadi error update data");
               System.out.println(e.getMessage());
           }
           Tabel.setModel(new DefaultTableModel(null, new String[]{
                    "ID", "No. Ktp", "No. Hp", "No. Kamar", "Nama 1", "Nama 2", "Jenis Kamar", "Tgl Checkin", "Tgl Checkout"
               }));

           loadData();
           TableColumnModel columnModel = Tabel.getColumnModel();
           columnModel.getColumn(0).setPreferredWidth(2);
           JOptionPane.showMessageDialog(this, "Data Berhasil Diubah");
           Tktp.setText("");
           Thp.setText("");
           Tkamar.setText("");
           Tnamasatu.setText("");
           Tnamadua.setText("");
           Tjeniskamar.setText("");
        }
    }//GEN-LAST:event_TubahMouseClicked
 int x = 210;
    int a = 0;
    private void Reservasi5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reservasi5ActionPerformed
        Reservasi reservasi = new Reservasi();
        reservasi.setVisible(true);
        reservasi.pack();
        reservasi.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_Reservasi5ActionPerformed

    private void Restoran5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Restoran5ActionPerformed
        // TODO add your handling code here:
        kasir_resto restoran = new kasir_resto();
        restoran.setVisible(true);
        restoran.pack();
        restoran.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_Restoran5ActionPerformed

    private void ThomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThomeMouseClicked
        Dashboard menu = new Dashboard();
        menu.setVisible(true);
        menu.pack();
        menu.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_ThomeMouseClicked

    private void TcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TcloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_TcloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ASC;
    private javax.swing.JCheckBox DESC;
    private javax.swing.JPanel Lmenu;
    private javax.swing.JPanel Lmenu1;
    private javax.swing.JPanel Lmenu2;
    private javax.swing.JPanel Lmenu3;
    private javax.swing.JPanel Lmenu4;
    private javax.swing.JPanel Lmenu5;
    private javax.swing.JLabel Menuside;
    private javax.swing.JLabel Menuside1;
    private javax.swing.JLabel Menuside2;
    private javax.swing.JLabel Menuside3;
    private javax.swing.JLabel Menuside4;
    private javax.swing.JLabel Menuside5;
    private javax.swing.JButton Reservasi;
    private javax.swing.JButton Reservasi1;
    private javax.swing.JButton Reservasi2;
    private javax.swing.JButton Reservasi3;
    private javax.swing.JButton Reservasi4;
    private javax.swing.JButton Reservasi5;
    private javax.swing.JButton Restoran;
    private javax.swing.JButton Restoran1;
    private javax.swing.JButton Restoran2;
    private javax.swing.JButton Restoran3;
    private javax.swing.JButton Restoran4;
    private javax.swing.JButton Restoran5;
    private javax.swing.JTable Tabel;
    private javax.swing.JTextField Tcari;
    private javax.swing.JLabel Tclose;
    private javax.swing.JButton Thome;
    private javax.swing.JTextField Thp;
    private javax.swing.JTextField Tjeniskamar;
    private javax.swing.JTextField Tkamar;
    private javax.swing.JTextField Tktp;
    private javax.swing.JTextField Tnamadua;
    private javax.swing.JTextField Tnamasatu;
    private javax.swing.JButton Tubah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cari;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> sort;
    // End of variables declaration//GEN-END:variables

}
