
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Togami
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        loadData();
    }
    
    
    static Connection koneksi;
    public static Connection getKoneksi() {
        try {
            String url = "jdbc:mysql://localhost:3306/perpustakaan";
            String user = "root";
            String password = "";
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            koneksi = DriverManager.getConnection(url, user, password);
        }catch (SQLException t){
            System.out.println("Error membuat koneksi");
        }
        return koneksi;
    }
    
    public void loadData(){
        try{
            Connection c = getKoneksi(); 
            Statement s = c.createStatement();
            String sql = "SELECT * FROM buku";
            ResultSet r = s.executeQuery(sql);
            while(r.next()){
              
              String data[] = {r.getString("kode"), r.getString("judul"), r.getString("pengarang"), r.getString("penerbit")};
       
              DefaultTableModel tblModel = (DefaultTableModel)Tabel.getModel();
              tblModel.addRow(data);
            }
            r.close();
            s.close();
        }catch(SQLException e){
            System.out.println("terjadi error");
        }
    }
    
    public void insertData(String kode, String judul, String pengarang, String penerbit){
        try{
            Connection c = getKoneksi(); 
            Statement s = c.createStatement();
            String sql = "INSERT INTO buku (kode, judul, pengarang, penerbit) VALUES ('%s', '%s', '%s', '%s')";
            sql = String.format(sql, kode, judul, pengarang, penerbit);
            s.execute(sql);
            
            
        }catch(SQLException e){
            System.out.println("terjadi error input data");
            System.out.println(e.getMessage());
        }
    }
    
    public void deleteData(String kode){
        try{
            Connection c = getKoneksi(); 
            Statement s = c.createStatement();
            String sql = String.format("DELETE FROM buku WHERE kode='%s'", kode);
            s.execute(sql);
        }catch(SQLException e){
            System.out.println("terjadi error delete data");
            System.out.println(e.getMessage());
        }
    }
    
    public void updateData(String kode, String judul, String pengarang, String penerbit, String kode2){
        try{
            Connection c = getKoneksi(); 
            Statement s = c.createStatement();
            String sql = "UPDATE buku SET kode='%s', judul='%s', pengarang='%s', penerbit='%s' WHERE kode='%s'";
            sql = String.format(sql, kode, judul, pengarang, penerbit, kode2);
            s.execute(sql);
        }catch(SQLException e){
            System.out.println("terjadi error update data");
            System.out.println(e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Tkode = new javax.swing.JTextField();
        Tjudul = new javax.swing.JTextField();
        Tpengarang = new javax.swing.JTextField();
        Tpenerbit = new javax.swing.JTextField();
        Ttambah = new javax.swing.JButton();
        Tubah = new javax.swing.JButton();
        Thapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kode Buku");

        jLabel2.setText("Judul Buku");

        jLabel3.setText("Pengarang");

        jLabel4.setText("Penerbit");

        Ttambah.setText("Tambah");
        Ttambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TtambahMouseClicked(evt);
            }
        });

        Tubah.setText("Ubah");
        Tubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TubahMouseClicked(evt);
            }
        });

        Thapus.setText("Hapus");
        Thapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThapusMouseClicked(evt);
            }
        });

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Buku", "Judul Buku", "Pengarang", "Penerbit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ttambah)
                        .addGap(18, 18, 18)
                        .addComponent(Tubah)
                        .addGap(18, 18, 18)
                        .addComponent(Thapus))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Tpenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Tpengarang)
                                    .addGap(1, 1, 1))
                                .addComponent(Tjudul, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(Tkode, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Tkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Tjudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Tpengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tpenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ttambah)
                    .addComponent(Tubah)
                    .addComponent(Thapus))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TtambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TtambahMouseClicked

       insertData(Tkode.getText(), Tjudul.getText(), Tpengarang.getText(), Tpenerbit.getText());
       Tabel.setModel(new DefaultTableModel(null, new String[]{
                "Kode Buku", "Judul Buku", "Pengarang", "Penerbit"
            }));
       Tjudul.setText("");
       Tkode.setText("");
       Tpengarang.setText("");
       Tpenerbit.setText("");
       JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan");
       loadData();
    }//GEN-LAST:event_TtambahMouseClicked

    private void ThapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThapusMouseClicked
        
        deleteData(Tkode.getText());
        Tabel.setModel(new DefaultTableModel(null, new String[]{
                "Kode Buku", "Judul Buku", "Pengarang", "Penerbit"
            }));
       Tjudul.setText("");
       Tkode.setText("");
       Tpengarang.setText("");
       Tpenerbit.setText("");
       JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
       loadData();
    }//GEN-LAST:event_ThapusMouseClicked

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked
        
        int row = Tabel.getSelectedRow();
        String value1 = Tabel.getModel().getValueAt(row, 0).toString();
        String value2 = Tabel.getModel().getValueAt(row, 1).toString();
        String value3 = Tabel.getModel().getValueAt(row, 2).toString();
        String value4 = Tabel.getModel().getValueAt(row, 3).toString();
        
        Tkode.setText(value1);
        Tjudul.setText(value2);
        Tpengarang.setText(value3);
        Tpenerbit.setText(value4);
    }//GEN-LAST:event_TabelMouseClicked

    private void TubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TubahMouseClicked
        int row = Tabel.getSelectedRow();
        String value = Tabel.getModel().getValueAt(row, 0).toString();
        updateData(Tkode.getText(), Tjudul.getText(), Tpengarang.getText(), Tpenerbit.getText(), value);
        Tabel.setModel(new DefaultTableModel(null, new String[]{
                "Kode Buku", "Judul Buku", "Pengarang", "Penerbit"
            }));
       Tjudul.setText("");
       Tkode.setText("");
       Tpengarang.setText("");
       Tpenerbit.setText("");
       JOptionPane.showMessageDialog(this, "Data Berhasil Diubah");
       loadData();
        
    }//GEN-LAST:event_TubahMouseClicked

  
    public static void main(String args[]) {
       
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel;
    private javax.swing.JButton Thapus;
    private javax.swing.JTextField Tjudul;
    private javax.swing.JTextField Tkode;
    private javax.swing.JTextField Tpenerbit;
    private javax.swing.JTextField Tpengarang;
    private javax.swing.JButton Ttambah;
    private javax.swing.JButton Tubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
